GET http://localhost:1323 HTTP/1.1
###
POST http://localhost:1323 HTTP/1.1
###
PUT http://localhost:1323 HTTP/1.1
###
DELETE http://localhost:1323 HTTP/1.1
###
GET http://localhost:1323/hello HTTP/1.1
###
POST http://localhost:1323/hello HTTP/1.1
###
PUT http://localhost:1323/hello HTTP/1.1
###
DELETE http://localhost:1323/hello HTTP/1.1