GET http://localhost:1323 HTTP/1.1
###
POST http://localhost:1323/login HTTP/1.1
Content-Type: application/json

{
    "email": "ethien.salinas@gmail.com",
    "password": "qwerty"
}
###
POST http://localhost:1323/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjAxNzU5MjU0LCJuYW1lIjoiIn0.ZZwCjlWyxUCrnf-N2-OzXSiNnIvit00Z52G-z8cv-ig
###
GET http://localhost:1323/users/ HTTP/1.1
###
GET http://localhost:1323/users/333 HTTP/1.1
###
PUT http://localhost:1323/users/333 HTTP/1.1
###
DELETE http://localhost:1323/users/ HTTP/1.1